module.exports = [ { names: [ 'Clipper', 'XBase' ],
    regexps: [ /^.+\.PRG$/, /^.+\.prg$/ ] },
  { names: [ 'Cucumber', 'cucumber', 'Gherkin', 'gherkin' ],
    regexps: [ /^.+\.feature$/ ] },
  { names: [ 'abap' ], regexps: [ /^.+\.abap$/ ] },
  { names: [ 'ada', 'ada95ada2005' ],
    regexps: [ /^.+\.adb$/, /^.+\.ads$/, /^.+\.ada$/ ] },
  { names: [ 'ahk' ], regexps: [ /^.+\.ahk$/, /^.+\.ahkl$/ ] },
  { names: [ 'antlr-as', 'antlr-actionscript' ],
    regexps: [ /^.+\.G$/, /^.+\.g$/ ] },
  { names: [ 'antlr-cpp' ], regexps: [ /^.+\.G$/, /^.+\.g$/ ] },
  { names: [ 'antlr-csharp', 'antlr-c#' ],
    regexps: [ /^.+\.G$/, /^.+\.g$/ ] },
  { names: [ 'antlr-java' ], regexps: [ /^.+\.G$/, /^.+\.g$/ ] },
  { names: [ 'antlr-objc' ], regexps: [ /^.+\.G$/, /^.+\.g$/ ] },
  { names: [ 'antlr-perl' ], regexps: [ /^.+\.G$/, /^.+\.g$/ ] },
  { names: [ 'antlr-python' ], regexps: [ /^.+\.G$/, /^.+\.g$/ ] },
  { names: [ 'antlr-ruby', 'antlr-rb' ],
    regexps: [ /^.+\.G$/, /^.+\.g$/ ] },
  { names: [ 'apacheconf', 'aconf', 'apache' ],
    regexps: [ /^\.htaccess$/, /^apache\.conf$/, /^apache2\.conf$/ ] },
  { names: [ 'applescript' ], regexps: [ /^.+\.applescript$/ ] },
  { names: [ 'as', 'actionscript' ], regexps: [ /^.+\.as$/ ] },
  { names: [ 'as3', 'actionscript3' ], regexps: [ /^.+\.as$/ ] },
  { names: [ 'aspectj' ], regexps: [ /^.+\.aj$/ ] },
  { names: [ 'aspx-cs' ],
    regexps:
     [ /^.+\.aspx$/,
       /^.+\.asax$/,
       /^.+\.ascx$/,
       /^.+\.ashx$/,
       /^.+\.asmx$/,
       /^.+\.axd$/ ] },
  { names: [ 'aspx-vb' ],
    regexps:
     [ /^.+\.aspx$/,
       /^.+\.asax$/,
       /^.+\.ascx$/,
       /^.+\.ashx$/,
       /^.+\.asmx$/,
       /^.+\.axd$/ ] },
  { names: [ 'asy', 'asymptote' ], regexps: [ /^.+\.asy$/ ] },
  { names: [ 'autoit', 'Autoit' ], regexps: [ /^.+\.au3$/ ] },
  { names: [ 'awk', 'gawk', 'mawk', 'nawk' ],
    regexps: [ /^.+\.awk$/ ] },
  { names: [ 'bash', 'sh', 'ksh' ],
    regexps:
     [ /^.+\.sh$/,
       /^.+\.ksh$/,
       /^.+\.bash$/,
       /^.+\.ebuild$/,
       /^.+\.eclass$/,
       /^\.bashrc$/,
       /^bashrc$/,
       /^\.bash_.+$/,
       /^bash_.+$/ ] },
  { names: [ 'bat' ], regexps: [ /^.+\.bat$/, /^.+\.cmd$/ ] },
  { names: [ 'befunge' ], regexps: [ /^.+\.befunge$/ ] },
  { names: [ 'blitzmax', 'bmax' ], regexps: [ /^.+\.bmx$/ ] },
  { names: [ 'boo' ], regexps: [ /^.+\.boo$/ ] },
  { names: [ 'brainfuck', 'bf' ],
    regexps: [ /^.+\.bf$/, /^.+\.b$/ ] },
  { names: [ 'bro' ], regexps: [ /^.+\.bro$/ ] },
  { names: [ 'bugs', 'winbugs', 'openbugs' ],
    regexps: [ /^.+\.bug$/ ] },
  { names: [ 'c-objdump' ], regexps: [ /^.+\.c-objdump$/ ] },
  { names: [ 'c' ],
    regexps: [ /^.+\.c$/, /^.+\.h$/, /^.+\.idc$/ ] },
  { names: [ 'ca65' ], regexps: [ /^.+\.s$/ ] },
  { names: [ 'cbmbas' ], regexps: [ /^.+\.bas$/ ] },
  { names: [ 'ceylon' ], regexps: [ /^.+\.ceylon$/ ] },
  { names: [ 'cfengine3', 'cf3' ], regexps: [ /^.+\.cf$/ ] },
  { names: [ 'cfm' ],
    regexps: [ /^.+\.cfm$/, /^.+\.cfml$/, /^.+\.cfc$/ ] },
  { names: [ 'cheetah', 'spitfire' ],
    regexps: [ /^.+\.tmpl$/, /^.+\.spt$/ ] },
  { names: [ 'clojure', 'clj' ], regexps: [ /^.+\.clj$/ ] },
  { names: [ 'cmake' ],
    regexps: [ /^.+\.cmake$/, /^CMakeLists\.txt$/ ] },
  { names: [ 'cobol' ],
    regexps: [ /^.+\.cob$/, /^.+\.COB$/, /^.+\.cpy$/, /^.+\.CPY$/ ] },
  { names: [ 'cobolfree' ],
    regexps: [ /^.+\.cbl$/, /^.+\.CBL$/ ] },
  { names: [ 'coffee-script', 'coffeescript' ],
    regexps: [ /^.+\.coffee$/ ] },
  { names: [ 'common-lisp', 'cl' ],
    regexps: [ /^.+\.cl$/, /^.+\.lisp$/, /^.+\.el$/ ] },
  { names: [ 'console' ], regexps: [ /^.+\.sh-session$/ ] },
  { names: [ 'control' ], regexps: [ /^control$/ ] },
  { names: [ 'coq' ], regexps: [ /^.+\.v$/ ] },
  { names: [ 'cpp', 'c++' ],
    regexps:
     [ /^.+\.cpp$/,
       /^.+\.hpp$/,
       /^.+\.c\+\+$/,
       /^.+\.h\+\+$/,
       /^.+\.cc$/,
       /^.+\.hh$/,
       /^.+\.cxx$/,
       /^.+\.hxx$/,
       /^.+\.C$/,
       /^.+\.H$/,
       /^.+\.cp$/,
       /^.+\.CPP$/ ] },
  { names: [ 'cpp-objdump', 'c++-objdumb', 'cxx-objdump' ],
    regexps:
     [ /^.+\.cpp-objdump$/,
       /^.+\.c\+\+-objdump$/,
       /^.+\.cxx-objdump$/ ] },
  { names: [ 'croc' ], regexps: [ /^.+\.croc$/ ] },
  { names: [ 'csharp', 'c#' ], regexps: [ /^.+\.cs$/ ] },
  { names: [ 'css' ], regexps: [ /^.+\.css$/ ] },
  { names: [ 'cuda', 'cu' ],
    regexps: [ /^.+\.cu$/, /^.+\.cuh$/ ] },
  { names: [ 'cython', 'pyx' ],
    regexps: [ /^.+\.pyx$/, /^.+\.pxd$/, /^.+\.pxi$/ ] },
  { names: [ 'd-objdump' ], regexps: [ /^.+\.d-objdump$/ ] },
  { names: [ 'd' ], regexps: [ /^.+\.d$/, /^.+\.di$/ ] },
  { names: [ 'dart' ], regexps: [ /^.+\.dart$/ ] },
  { names: [ 'delphi', 'pas', 'pascal', 'objectpascal' ],
    regexps: [ /^.+\.pas$/ ] },
  { names: [ 'dg' ], regexps: [ /^.+\.dg$/ ] },
  { names: [ 'diff', 'udiff' ],
    regexps: [ /^.+\.diff$/, /^.+\.patch$/ ] },
  { names: [ 'dpatch' ],
    regexps: [ /^.+\.dpatch$/, /^.+\.darcspatch$/ ] },
  { names: [ 'dtd' ], regexps: [ /^.+\.dtd$/ ] },
  { names: [ 'duel', 'Duel Engine', 'Duel View', 'JBST', 'jbst', 'JsonML+BST' ],
    regexps: [ /^.+\.duel$/, /^.+\.jbst$/ ] },
  { names: [ 'dylan-lid', 'lid' ],
    regexps: [ /^.+\.lid$/, /^.+\.hdp$/ ] },
  { names: [ 'dylan' ],
    regexps: [ /^.+\.dylan$/, /^.+\.dyl$/, /^.+\.intr$/ ] },
  { names: [ 'ec' ], regexps: [ /^.+\.ec$/, /^.+\.eh$/ ] },
  { names: [ 'ecl' ], regexps: [ /^.+\.ecl$/ ] },
  { names: [ 'elixir', 'ex', 'exs' ],
    regexps: [ /^.+\.ex$/, /^.+\.exs$/ ] },
  { names: [ 'erl' ], regexps: [ /^.+\.erl-sh$/ ] },
  { names: [ 'erlang' ],
    regexps: [ /^.+\.erl$/, /^.+\.hrl$/, /^.+\.es$/, /^.+\.escript$/ ] },
  { names: [ 'evoque' ], regexps: [ /^.+\.evoque$/ ] },
  { names: [ 'factor' ], regexps: [ /^.+\.factor$/ ] },
  { names: [ 'fan' ], regexps: [ /^.+\.fan$/ ] },
  { names: [ 'fancy', 'fy' ],
    regexps: [ /^.+\.fy$/, /^.+\.fancypack$/ ] },
  { names: [ 'felix', 'flx' ],
    regexps: [ /^.+\.flx$/, /^.+\.flxh$/ ] },
  { names: [ 'fortran' ],
    regexps: [ /^.+\.f$/, /^.+\.f90$/, /^.+\.F$/, /^.+\.F90$/ ] },
  { names: [ 'fsharp' ], regexps: [ /^.+\.fs$/, /^.+\.fsi$/ ] },
  { names: [ 'gas' ], regexps: [ /^.+\.s$/, /^.+\.S$/ ] },
  { names: [ 'genshi', 'kid', 'xml+genshi', 'xml+kid' ],
    regexps: [ /^.+\.kid$/ ] },
  { names: [ 'glsl' ],
    regexps: [ /^.+\.vert$/, /^.+\.frag$/, /^.+\.geo$/ ] },
  { names: [ 'gnuplot' ], regexps: [ /^.+\.plot$/, /^.+\.plt$/ ] },
  { names: [ 'go' ], regexps: [ /^.+\.go$/ ] },
  { names: [ 'gooddata-cl' ], regexps: [ /^.+\.gdc$/ ] },
  { names: [ 'gosu' ],
    regexps: [ /^.+\.gs$/, /^.+\.gsx$/, /^.+\.gsp$/, /^.+\.vark$/ ] },
  { names: [ 'groff', 'nroff', 'man' ],
    regexps: [ /^.+\.[1234567]$/, /^.+\.man$/ ] },
  { names: [ 'groovy' ], regexps: [ /^.+\.groovy$/ ] },
  { names: [ 'gst' ], regexps: [ /^.+\.gst$/ ] },
  { names: [ 'haml', 'HAML' ], regexps: [ /^.+\.haml$/ ] },
  { names: [ 'haskell', 'hs' ], regexps: [ /^.+\.hs$/ ] },
  { names: [ 'haxeml', 'hxml' ], regexps: [ /^.+\.hxml$/ ] },
  { names: [ 'html+php' ], regexps: [ /^.+\.phtml$/ ] },
  { names: [ 'hx', 'haXe' ], regexps: [ /^.+\.hx$/ ] },
  { names: [ 'hybris', 'hy' ],
    regexps: [ /^.+\.hy$/, /^.+\.hyb$/ ] },
  { names: [ 'idl' ], regexps: [ /^.+\.pro$/ ] },
  { names: [ 'ini', 'cfg' ],
    regexps: [ /^.+\.ini$/, /^.+\.cfg$/ ] },
  { names: [ 'io' ], regexps: [ /^.+\.io$/ ] },
  { names: [ 'ioke', 'ik' ], regexps: [ /^.+\.ik$/ ] },
  { names: [ 'irc' ], regexps: [ /^.+\.weechatlog$/ ] },
  { names: [ 'jade', 'JADE' ], regexps: [ /^.+\.jade$/ ] },
  { names: [ 'jags' ], regexps: [ /^.+\.jag$/, /^.+\.bug$/ ] },
  { names: [ 'java' ], regexps: [ /^.+\.java$/ ] },
  { names: [ 'js', 'javascript' ], regexps: [ /^.+\.js$/ ] },
  { names: [ 'json' ], regexps: [ /^.+\.json$/ ] },
  { names: [ 'jsp' ], regexps: [ /^.+\.jsp$/ ] },
  { names: [ 'julia', 'jl' ], regexps: [ /^.+\.jl$/ ] },
  { names: [ 'kconfig', 'menuconfig', 'linux-config', 'kernel-config' ],
    regexps:
     [ /^Kconfig$/,
       /^.+Config\.in.+$/,
       /^external\.in.+$/,
       /^standard-modules\.in$/ ] },
  { names: [ 'koka' ], regexps: [ /^.+\.kk$/, /^.+\.kki$/ ] },
  { names: [ 'kotlin' ], regexps: [ /^.+\.kt$/ ] },
  { names: [ 'lasso', 'lassoscript' ],
    regexps: [ /^.+\.lasso$/, /^.+\.lasso[89]$/ ] },
  { names: [ 'lhs', 'literate-haskell' ],
    regexps: [ /^.+\.lhs$/ ] },
  { names: [ 'live-script', 'livescript' ],
    regexps: [ /^.+\.ls$/ ] },
  { names: [ 'llvm' ], regexps: [ /^.+\.ll$/ ] },
  { names: [ 'logtalk' ], regexps: [ /^.+\.lgt$/ ] },
  { names: [ 'lua' ], regexps: [ /^.+\.lua$/, /^.+\.wlua$/ ] },
  { names: [ 'make', 'makefile', 'mf', 'bsdmake' ],
    regexps:
     [ /^.+\.mak$/,
       /^Makefile$/,
       /^makefile$/,
       /^Makefile\..+$/,
       /^GNUmakefile$/ ] },
  { names: [ 'mako' ], regexps: [ /^.+\.mao$/ ] },
  { names: [ 'maql' ], regexps: [ /^.+\.maql$/ ] },
  { names: [ 'mason' ],
    regexps:
     [ /^.+\.m$/,
       /^.+\.mhtml$/,
       /^.+\.mc$/,
       /^.+\.mi$/,
       /^autohandler$/,
       /^dhandler$/ ] },
  { names: [ 'matlab' ], regexps: [ /^.+\.m$/ ] },
  { names: [ 'markdown' ], regexps: [ /^.+\.md$/i, /^.+\.markdown$/i ] },
  { names: [ 'modelica' ], regexps: [ /^.+\.mo$/ ] },
  { names: [ 'modula2', 'm2' ],
    regexps: [ /^.+\.def$/, /^.+\.mod$/ ] },
  { names: [ 'monkey' ], regexps: [ /^.+\.monkey$/ ] },
  { names: [ 'moocode' ], regexps: [ /^.+\.moo$/ ] },
  { names: [ 'moon', 'moonscript' ], regexps: [ /^.+\.moon$/ ] },
  { names: [ 'mscgen', 'msc' ], regexps: [ /^.+\.msc$/ ] },
  { names: [ 'mupad' ], regexps: [ /^.+\.mu$/ ] },
  { names: [ 'mxml' ], regexps: [ /^.+\.mxml$/ ] },
  { names: [ 'myghty' ],
    regexps: [ /^.+\.myt$/, /^autodelegate$/ ] },
  { names: [ 'nasm' ], regexps: [ /^.+\.asm$/, /^.+\.ASM$/ ] },
  { names: [ 'nemerle' ], regexps: [ /^.+\.n$/ ] },
  { names: [ 'newlisp' ], regexps: [ /^.+\.lsp$/, /^.+\.nl$/ ] },
  { names: [ 'newspeak' ], regexps: [ /^.+\.ns2$/ ] },
  { names: [ 'nimrod', 'nim' ],
    regexps: [ /^.+\.nim$/, /^.+\.nimrod$/ ] },
  { names: [ 'nsis', 'nsi', 'nsh' ],
    regexps: [ /^.+\.nsi$/, /^.+\.nsh$/ ] },
  { names: [ 'objdump' ], regexps: [ /^.+\.objdump$/ ] },
  { names: [ 'objective-c++', 'objectivec++', 'obj-c++', 'objc++' ],
    regexps: [ /^.+\.mm$/, /^.+\.hh$/ ] },
  { names: [ 'objective-c', 'objectivec', 'obj-c', 'objc' ],
    regexps: [ /^.+\.m$/, /^.+\.h$/ ] },
  { names: [ 'objective-j', 'objectivej', 'obj-j', 'objj' ],
    regexps: [ /^.+\.j$/ ] },
  { names: [ 'ocaml' ],
    regexps: [ /^.+\.ml$/, /^.+\.mli$/, /^.+\.mll$/, /^.+\.mly$/ ] },
  { names: [ 'octave' ], regexps: [ /^.+\.m$/ ] },
  { names: [ 'ooc' ], regexps: [ /^.+\.ooc$/ ] },
  { names: [ 'opa' ], regexps: [ /^.+\.opa$/ ] },
  { names: [ 'openedge', 'abl', 'progress' ],
    regexps: [ /^.+\.p$/, /^.+\.cls$/ ] },
  { names: [ 'perl', 'pl' ], regexps: [ /^.+\.pl$/, /^.+\.pm$/ ] },
  { names: [ 'php', 'php3', 'php4', 'php5' ],
    regexps: [ /^.+\.php$/, /^.+\.php[345]$/ ] },
  { names: [ 'pov' ], regexps: [ /^.+\.pov$/, /^.+\.inc$/ ] },
  { names: [ 'powershell', 'posh', 'ps1' ],
    regexps: [ /^.+\.ps1$/ ] },
  { names: [ 'prolog' ],
    regexps: [ /^.+\.prolog$/, /^.+\.pro$/, /^.+\.pl$/ ] },
  { names: [ 'properties' ], regexps: [ /^.+\.properties$/ ] },
  { names: [ 'protobuf' ], regexps: [ /^.+\.proto$/ ] },
  { names: [ 'puppet' ], regexps: [ /^.+\.pp$/ ] },
  { names: [ 'py3tb' ], regexps: [ /^.+\.py3tb$/ ] },
  { names: [ 'pypylog', 'pypy' ], regexps: [ /^.+\.pypylog$/ ] },
  { names: [ 'pytb' ], regexps: [ /^.+\.pytb$/ ] },
  { names: [ 'python', 'py', 'sage' ],
    regexps:
     [ /^.+\.py$/,
       /^.+\.pyw$/,
       /^.+\.sc$/,
       /^SConstruct$/,
       /^SConscript$/,
       /^.+\.tac$/,
       /^.+\.sage$/ ] },
  { names: [ 'qml', 'Qt Meta Language', 'Qt modeling Language' ],
    regexps: [ /^.+\.qml$/ ] },
  { names: [ 'racket', 'rkt' ],
    regexps: [ /^.+\.rkt$/, /^.+\.rktl$/ ] },
  { names: [ 'ragel-c' ], regexps: [ /^.+\.rl$/ ] },
  { names: [ 'ragel-cpp' ], regexps: [ /^.+\.rl$/ ] },
  { names: [ 'ragel-d' ], regexps: [ /^.+\.rl$/ ] },
  { names: [ 'ragel-em' ], regexps: [ /^.+\.rl$/ ] },
  { names: [ 'ragel-java' ], regexps: [ /^.+\.rl$/ ] },
  { names: [ 'ragel-objc' ], regexps: [ /^.+\.rl$/ ] },
  { names: [ 'ragel-ruby', 'ragel-rb' ], regexps: [ /^.+\.rl$/ ] },
  { names: [ 'rb', 'ruby', 'duby' ],
    regexps:
     [ /^.+\.rb$/,
       /^.+\.rbw$/,
       /^Rakefile$/,
       /^.+\.rake$/,
       /^.+\.gemspec$/,
       /^.+\.rbx$/,
       /^.+\.duby$/ ] },
  { names: [ 'rconsole', 'rout' ], regexps: [ /^.+\.Rout$/ ] },
  { names: [ 'rd' ], regexps: [ /^.+\.Rd$/ ] },
  { names: [ 'rebol' ], regexps: [ /^.+\.r$/, /^.+\.r3$/ ] },
  { names: [ 'redcode' ], regexps: [ /^.+\.cw$/ ] },
  { names: [ 'rhtml', 'html+erb', 'html+ruby' ],
    regexps: [ /^.+\.rhtml$/ ] },
  { names: [ 'rst', 'rest', 'restructuredtext' ],
    regexps: [ /^.+\.rst$/, /^.+\.rest$/ ] },
  { names: [ 'rust' ], regexps: [ /^.+\.rs$/, /^.+\.rc$/ ] },
  { names: [ 'sass', 'SASS' ], regexps: [ /^.+\.sass$/ ] },
  { names: [ 'scala' ], regexps: [ /^.+\.scala$/ ] },
  { names: [ 'scaml', 'SCAML' ], regexps: [ /^.+\.scaml$/ ] },
  { names: [ 'scheme', 'scm' ],
    regexps: [ /^.+\.scm$/, /^.+\.ss$/ ] },
  { names: [ 'scilab' ],
    regexps: [ /^.+\.sci$/, /^.+\.sce$/, /^.+\.tst$/ ] },
  { names: [ 'scss' ], regexps: [ /^.+\.scss$/ ] },
  { names: [ 'smali' ], regexps: [ /^.+\.smali$/ ] },
  { names: [ 'smalltalk', 'squeak' ], regexps: [ /^.+\.st$/ ] },
  { names: [ 'smarty' ], regexps: [ /^.+\.tpl$/ ] },
  { names: [ 'sml' ],
    regexps: [ /^.+\.sml$/, /^.+\.sig$/, /^.+\.fun$/ ] },
  { names: [ 'snobol' ], regexps: [ /^.+\.snobol$/ ] },
  { names: [ 'sourceslist', 'sources.list' ],
    regexps: [ /^sources\.list$/ ] },
  { names: [ 'sp' ], regexps: [ /^.+\.sp$/ ] },
  { names: [ 'spec' ], regexps: [ /^.+\.spec$/ ] },
  { names: [ 'splus', 's', 'r' ],
    regexps: [ /^.+\.S$/, /^.+\.R$/, /^\.Rhistory$/, /^\.Rprofile$/ ] },
  { names: [ 'sql' ], regexps: [ /^.+\.sql$/ ] },
  { names: [ 'sqlite3' ], regexps: [ /^.+\.sqlite3-console$/ ] },
  { names: [ 'squidconf', 'squid.conf', 'squid' ],
    regexps: [ /^squid\.conf$/ ] },
  { names: [ 'ssp' ], regexps: [ /^.+\.ssp$/ ] },
  { names: [ 'stan' ], regexps: [ /^.+\.stan$/ ] },
  { names: [ 'sv' ], regexps: [ /^.+\.sv$/, /^.+\.svh$/ ] },
  { names: [ 'tcl' ], regexps: [ /^.+\.tcl$/ ] },
  { names: [ 'tcsh', 'csh' ],
    regexps: [ /^.+\.tcsh$/, /^.+\.csh$/ ] },
  { names: [ 'tea' ], regexps: [ /^.+\.tea$/ ] },
  { names: [ 'tex', 'latex' ],
    regexps: [ /^.+\.tex$/, /^.+\.aux$/, /^.+\.toc$/ ] },
  { names: [ 'text' ], regexps: [ /^.+\.txt$/ ] },
  { names: [ 'treetop' ],
    regexps: [ /^.+\.treetop$/, /^.+\.tt$/ ] },
  { names: [ 'ts' ], regexps: [ /^.+\.ts$/ ] },
  { names: [ 'urbiscript' ], regexps: [ /^.+\.u$/ ] },
  { names: [ 'v' ], regexps: [ /^.+\.v$/ ] },
  { names: [ 'vala', 'vapi' ],
    regexps: [ /^.+\.vala$/, /^.+\.vapi$/ ] },
  { names: [ 'vb.net', 'vbnet' ],
    regexps: [ /^.+\.vb$/, /^.+\.bas$/ ] },
  { names: [ 'velocity' ],
    regexps: [ /^.+\.vm$/, /^.+\.fhtml$/ ] },
  { names: [ 'vgl' ], regexps: [ /^.+\.rpf$/ ] },
  { names: [ 'vhdl' ], regexps: [ /^.+\.vhdl$/, /^.+\.vhd$/ ] },
  { names: [ 'vim' ],
    regexps:
     [ /^.+\.vim$/,
       /^\.vimrc$/,
       /^\.exrc$/,
       /^\.gvimrc$/,
       /^_vimrc$/,
       /^_exrc$/,
       /^_gvimrc$/,
       /^vimrc$/,
       /^gvimrc$/ ] },
  { names: [ 'xml+evoque' ], regexps: [ /^.+\.xml$/ ] },
  { names: [ 'xml' ],
    regexps:
     [ /^.+\.xml$/,
       /^.+\.xsl$/,
       /^.+\.rss$/,
       /^.+\.xslt$/,
       /^.+\.xsd$/,
       /^.+\.wsdl$/ ] },
  { names: [ 'xquery', 'xqy', 'xq', 'xql', 'xqm' ],
    regexps:
     [ /^.+\.xqy$/,
       /^.+\.xquery$/,
       /^.+\.xq$/,
       /^.+\.xql$/,
       /^.+\.xqm$/ ] },
  { names: [ 'xslt' ],
    regexps: [ /^.+\.xsl$/, /^.+\.xslt$/, /^.+\.xpl$/ ] },
  { names: [ 'xtend' ], regexps: [ /^.+\.xtend$/ ] },
  { names: [ 'yaml' ], regexps: [ /^.+\.yaml$/, /^.+\.yml$/ ] } ]
